from PyQt5 import QtCore, QtGui, QtWidgets

class QVSEDMainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 420)
        font = QtGui.QFont()
        font.setFamily("monospace")
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.mainLayout = QtWidgets.QVBoxLayout()
        self.mainLayout.setContentsMargins(8, 8, 8, 8)
        self.mainLayout.setSpacing(8)
        self.mainLayout.setObjectName("mainLayout")
        self.elementsLayout = QtWidgets.QHBoxLayout()
        self.elementsLayout.setObjectName("elementsLayout")
        self.actionDeck = QtWidgets.QVBoxLayout()
        self.actionDeck.setObjectName("actionDeck")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setMinimumSize(QtCore.QSize(175, 40))
        self.clearButton.setMaximumSize(QtCore.QSize(161, 40))
        font = QtGui.QFont()
        font.setFamily("monospace")
        font.setPointSize(11)
        self.clearButton.setFont(font)
        self.clearButton.setFlat(False)
        self.clearButton.setObjectName("clearButton")
        self.actionDeck.addWidget(self.clearButton)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setMinimumSize(QtCore.QSize(175, 40))
        self.saveButton.setMaximumSize(QtCore.QSize(161, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.saveButton.setFont(font)
        self.saveButton.setFlat(False)
        self.saveButton.setObjectName("saveButton")
        self.actionDeck.addWidget(self.saveButton)
        self.openButton = QtWidgets.QPushButton(self.centralwidget)
        self.openButton.setMinimumSize(QtCore.QSize(175, 40))
        self.openButton.setMaximumSize(QtCore.QSize(161, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.openButton.setFont(font)
        self.openButton.setFlat(False)
        self.openButton.setObjectName("openButton")
        self.actionDeck.addWidget(self.openButton)
        self.fullscreenButton = QtWidgets.QPushButton(self.centralwidget)
        self.fullscreenButton.setMinimumSize(QtCore.QSize(175, 40))
        self.fullscreenButton.setMaximumSize(QtCore.QSize(161, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fullscreenButton.setFont(font)
        self.fullscreenButton.setFlat(False)
        self.fullscreenButton.setObjectName("fullscreenButton")
        self.actionDeck.addWidget(self.fullscreenButton)
        spacerItem = QtWidgets.QSpacerItem(
            20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding
        )
        self.actionDeck.addItem(spacerItem)
        self.helpButton = QtWidgets.QPushButton(self.centralwidget)
        self.helpButton.setMinimumSize(QtCore.QSize(175, 40))
        self.helpButton.setMaximumSize(QtCore.QSize(161, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.helpButton.setFont(font)
        self.helpButton.setFlat(False)
        self.helpButton.setObjectName("helpButton")
        self.actionDeck.addWidget(self.helpButton)
        self.quitButton = QtWidgets.QPushButton(self.centralwidget)
        self.quitButton.setMinimumSize(QtCore.QSize(175, 40))
        self.quitButton.setMaximumSize(QtCore.QSize(161, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.quitButton.setFont(font)
        self.quitButton.setFlat(False)
        self.quitButton.setObjectName("quitButton")
        self.actionDeck.addWidget(self.quitButton)
        self.elementsLayout.addLayout(self.actionDeck)
        self.textArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.textArea.setFont(font)
        self.textArea.setObjectName("textArea")
        self.elementsLayout.addWidget(self.textArea)
        self.mainLayout.addLayout(self.elementsLayout)
        self.echoArea = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.echoArea.setFont(font)
        self.echoArea.setCursorPosition(0)
        self.echoArea.setReadOnly(True)
        self.echoArea.setObjectName("echoArea")
        self.mainLayout.addWidget(self.echoArea)
        self.horizontalLayout_4.addLayout(self.mainLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "QVSED"))
        self.clearButton.setText(_translate("MainWindow", "Clear Text <C-n>"))
        self.saveButton.setText(_translate("MainWindow", "Save File <C-s>"))
        self.openButton.setText(_translate("MainWindow", "Open File <C-f>"))
        self.fullscreenButton.setText(_translate("MainWindow", "Full Screen <A-f>"))
        self.helpButton.setText(_translate("MainWindow", "Get Help <C-h>"))
        self.quitButton.setText(_translate("MainWindow", "Quit QVSED <A-q>"))

class QVSEDMainDialog(object):
    def setupUi(self, FileDialog):
        FileDialog.setObjectName("FileDialog")
        FileDialog.resize(795, 214)
        FileDialog.setSizeGripEnabled(False)
        FileDialog.setModal(False)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(FileDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainLabel = QtWidgets.QLabel(FileDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.mainLabel.setFont(font)
        self.mainLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLabel.setObjectName("mainLabel")
        self.verticalLayout.addWidget(self.mainLabel)
        self.cwdLabel = QtWidgets.QLabel(FileDialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cwdLabel.setFont(font)
        self.cwdLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cwdLabel.setObjectName("cwdLabel")
        self.verticalLayout.addWidget(self.cwdLabel)
        self.filePathBox = QtWidgets.QLineEdit(FileDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.filePathBox.setFont(font)
        self.filePathBox.setStyleSheet("padding: 8px")
        self.filePathBox.setObjectName("filePathBox")
        self.verticalLayout.addWidget(self.filePathBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(8)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openSystemDialogButton = QtWidgets.QPushButton(FileDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.openSystemDialogButton.setFont(font)
        self.openSystemDialogButton.setStyleSheet("padding: 10px 17px")
        self.openSystemDialogButton.setAutoDefault(False)
        self.openSystemDialogButton.setObjectName("openSystemDialogButton")
        self.horizontalLayout.addWidget(self.openSystemDialogButton)
        self.chdirButton = QtWidgets.QPushButton(FileDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.chdirButton.setFont(font)
        self.chdirButton.setStyleSheet("padding: 10px 17px")
        self.chdirButton.setAutoDefault(False)
        self.chdirButton.setFlat(False)
        self.chdirButton.setObjectName("chdirButton")
        self.horizontalLayout.addWidget(self.chdirButton)
        spacerItem = QtWidgets.QSpacerItem(
            80, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.confirmButton = QtWidgets.QPushButton(FileDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.confirmButton.setFont(font)
        self.confirmButton.setStyleSheet("padding: 10px 17px")
        self.confirmButton.setObjectName("confirmButton")
        self.horizontalLayout.addWidget(self.confirmButton)
        self.cancelButton = QtWidgets.QPushButton(FileDialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancelButton.setFont(font)
        self.cancelButton.setStyleSheet("padding: 10px 17px")
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(FileDialog)
        QtCore.QMetaObject.connectSlotsByName(FileDialog)

    def retranslateUi(self, FileDialog):
        _translate = QtCore.QCoreApplication.translate
        FileDialog.setWindowTitle(_translate("FileDialog", "Dialog"))
        self.mainLabel.setText(
            _translate(
                "FileDialog", "Enter the file path to use (relative or absolute)"
            )
        )
        self.cwdLabel.setText(
            _translate("FileDialog", "Current working directory is <cwd>")
        )
        self.openSystemDialogButton.setText(
            _translate("FileDialog", "System File Picker <C-d>")
        )
        self.chdirButton.setText(_translate("FileDialog", "Change Directory <A-d>"))
        self.confirmButton.setText(_translate("FileDialog", "Confirm"))
        self.cancelButton.setText(_translate("FileDialog", "Cancel"))
